# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Mrs. Money Bee
tagline: tagline
description: > # this means to ignore newlines until next
  Mrs. Money Bee
url: "https://mrsmoneybee.github.io" # the base hostname & protocol for your site
baseurl: "" # the subpath of your site, e.g. /blog

owner:
  name: Mrs. Money Bee
  avatar: avatar.png
  email: themrsmoneybee@gmail.com
  twitter: themrsmoneybee
  disqus: mrsmoneybee

# Links to include in top nav
# External add "external: true"
links:
  - title: About
    url: /about
  # - title: Github
  #   url: https://github.com/ColeTownsend/Balzac-for-Jekyll
  #   external: true
  # - title: Cole Who?
  #   url: http://coletownsend.com
  #   external: true

# Global settings
opengraph:
  locale: en_US
timezone: America/New_York

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  hard_wrap: false

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink: /:year/:month/:day/:title.html
excerpt_separator: <!--more-->

gems:
- jemoji
- jekyll-feed
- jekyll-paginate
- jekyll-seo-tag
- jekyll-sitemap

exclude:
- Gemfile
- Gemfile.lock
- LICENSE
- README.md
- CNAME